### ISSUE TITLE
Dataset generation timing

### ISSUE THREAD

**Issue by JeffersonAero** [RMDLO/COCOpen-OpenCV#10]
This is not related to structure of code, but is related to user-friendliness: it would be helpful to aggregate total computation time of each function to see which portions of dataset creation take the most time and to target dataset generation optimization.

**Comment by JeffersonAero** [comment]
Are there any plots we can generate related to this? It would be helpful to include as an evaluation of our work in the report.

**Comment by ambulocetus18** [comment]
I ran the scripts to generate 10 train images + 10 val images and here are the stats:
![Screenshot from 2022-12-08 12-50-44](https://user-images.githubusercontent.com/97369518/206542538-78dc0b22-44c4-49da-b288-8576d5d7f60f.png)
It seems like the most time consuming ones are color augmentation and download images from azure

**Comment by ambulocetus18** [comment]
A diagram (draft) showing the structure of the program:
![image](https://user-images.githubusercontent.com/97369518/206586309-4da88215-ded5-44ad-b674-d741904e0b48.png)

**Comment by ambulocetus18** [comment]
A pie chart:
<img width="571" alt="Screenshot 2022-12-08 201106" src="https://user-images.githubusercontent.com/97369518/206608003-3046e1fb-f7d6-42cd-9fef-048eeac40e65.png">
