### ISSUE TITLE
Collect 100 images of devices against black background and add to original dataset

### ISSUE THREAD

**Issue by JeffersonAero** [RMDLO/COCOpen-OpenCV#13]
- Collect images, upload to "device" folder on azure
- Rename "single-wire" folder on azure to "wire"
- Read object category from its storage folder/container on azure
- Tune device segmentation (color threshold values)

Purpose: generate the method can scale to _N_ object categories by demonstrating it works for two.

**Comment by JeffersonAero** [comment]
- Collected 200 images of 3 types of ethernet device and saved to `device.zip` folder on Google Drive.
- Renamed all images in `single_wire.zip` folder on Google Drive so that there are no gaps in image numbering and so that the image numbering is more intuitive.
- Renamed all images in `backgrounds.zip` folder on Google Drive
- Renamed `single_wire` images folder to `wire.zip`. It is cleaner to specify object categories as single words.
- All `.zip` files representing our data are now under the [`RMDLO/datasets/COCOpen/`](https://drive.google.com/drive/folders/1Pmu3Xx941WuixNsocUI76u4fR6hA4WHm?usp=share_link) directory on Google Drive. 
- Device segmentation color threshold values were tuned to visualize approximate segmentation during image collection. See lines 49-59 of [singleshot.py](https://github.com/RMDLO/astrobee_ws/blob/main/src/dataset_collection/node/singleshot.py) (the key threshold value is `180` in line 42).

**TODO Still**
- upload new dataset to azure (@yrraadi-io )
- add device segmentation to COCOpen-OpenCV
- read object category from its storage folder (?)

**Comment by yrraadi-io** [comment]
- Uploaded devices, backgrounds to Azure.
- Wires folder was taking too long to extract on my computer, will have to do it in B-16.

**Comment by JeffersonAero** [comment]
I added a list of object categories to `config/parameters.yml`. Can we iterate through the list of object categories to automatically generate the ```foreground_image_[object]_container```? Generalizing container access for _N_ objects such that a user does not have to manually manage a length _N_ list of containers and duplicate several functions is the last **TODO** before we can close this issue.

**Comment by JeffersonAero** [comment]
I realize now a major difference in lighting configuration between the single wire and single device image collection processes. If there is time I may try to fix (after resolving other issues first).

**Comment by JeffersonAero** [comment]
> I realize now a major difference in lighting configuration between the single wire and single device image collection processes. If there is time I may try to fix (after resolving other issues first).

Generated a new device dataset -> fixed.

**Comment by yrraadi-io** [comment]
Closing these issues with this comment

https://github.com/RMDLO/COCOpen-OpenCV/commit/8137f2a7776fa3b6c7dbe1d6820fb4507888b66f
