### ISSUE TITLE
Add docstrings to modules, classes, and functions in cocopen.py

### ISSUE THREAD

**Issue by zhao-harry** [RMDLO/COCOpen-OpenCV#21]
Explain functionality, variables, and I/O associated with modules, classes, and functions in `cocopen.py`.

**Comment by JeffersonAero** [comment]
These two resources provide helpful details on standard docstring formatting:
- https://www.programiz.com/python-programming/docstrings
- https://www.datacamp.com/tutorial/docstrings-python

**Comment by JeffersonAero** [comment]
I added docstrings to `src/train.py` and `src/demo.py` and performed `flake8` and `pylint` on these scripts to ensure resolution of missing docstring issues. These were merged to main in #50. Both scripts are still missing module docstrings in line 1 ("Missing module docstring (missing-module-docstring)").

**Comment by zhao-harry** [comment]
I added the remaining docstrings for `demo.py` and made formatting fixes. Changes have been pushed to `review`.
