### ISSUE TITLE
Remove pillow dependency?

### ISSUE THREAD

**Issue by JeffersonAero** [RMDLO/COCOpen-OpenCV#28]
We have a dependency on pillow, `hsv_img = Image.fromarray(rgb_img)`. It would be better to remove pillow dependencies and only use opencv dependencies. If we use opencv for this, we need to make sure to `conda uninstall pillow` and upload new `environment.yml` files.

**Comment by zhao-harry** [comment]
I substituted PIL `ImageEnhance` functions using OpenCV and removed all traces of PIL from `cocopen.py`. I'm not able to generate the proper environment files on my machine, so I'm leaving this issue open until that is resolved.

**Comment by JeffersonAero** [comment]
I regenerated all environment files. It looks like pillow is still a dependency for another library. Closing this issue since it seems resolved on our end.
