### ISSUE TITLE
Black pixels around every object in generated dataset

### ISSUE THREAD

**Issue by JeffersonAero** [RMDLO/COCOpen-OpenCV#49]
Because the edge pixels of every object may have been lighter than the color threshold (some mix of the color of the object and the color of the background - black), the edge pixels were not filtered out. Every generated object image in the dataset includes black outlines around the object. We could use alpha matting or a similar technique to remove this outline - [similar to this post](https://stackoverflow.com/questions/73147308/python-how-do-you-reduce-get-rid-of-the-edge-of-an-item-inside-a-clearcut-imag) and [this post](https://helpx.adobe.com/after-effects/using/alpha-channels-masks-mattes.html).
![image](https://user-images.githubusercontent.com/40707210/207910377-7ed0b5ab-23cf-4af6-99a8-861b0a5b44cb.png)

**Comment by ambulocetus18** [comment]
Added extra lines to remove the dark object outlines in commit [f606d8f](https://github.com/RMDLO/COCOpen-OpenCV/commit/f606d8fbb32645789856e8af7470ee19abea2bd8). 
A side by side comparison of with and without outline removal:
![image](https://user-images.githubusercontent.com/97369518/208024570-7e299b15-5513-408b-9845-e6e2ab971a74.png)
