### ISSUE TITLE
Modify hard-coded image dimensions and train/val split

### ISSUE THREAD

**Issue by JeffersonAero** [RMDLO/COCOpen-OpenCV#7]
Image dimensions are currently hard-coded throughout cocopen.py (height = 1080, width = 1920). Need to replace these with a class variable self.height and self.width. It would be helpful to have a function that checks to make sure all images used to generate the dataset are the same dimensions before beginning the image combination - should throw an exception if image dimensions are not consistent. This function could be included in a dataset preprocessing script (i.e., not in coconut.py).

Note: This affects the scale_image, random_operations, and color_augmentation functions in coconut.py where image dimensions are hard-coded

Train/val split is currently hard-coded as 0.8 in two locations. It would be better to let the user define their train/val split (some users may want a 0.9/0.1 split, for example). Assign this to a class variable and/or read it in from run.py.
```
if 0 <= rand < 0.8:
```

**Comment by JeffersonAero** [comment]
Added dataset_parameters: train_split: 0.8 in `./config/parameters.yml` file. Still need to read in image dimensions from `./config/parameters.yml` and verify all images used in the data set have the same dimensions before performing `combine()`.

**Comment by zhao-harry** [comment]
#22
