### ISSUE TITLE
Combine function jittering

### ISSUE THREAD

**Issue by JeffersonAero** [RMDLO/COCOpen-OpenCV#8]
In the combine function, we have several augmentation methods all in one function. It would be helpful to set the boolean for these as a class variable (e.g., self.standard_scale_jittering=False) rather than hard-coded within the function (lines 391-401 in commit [42782ee](https://github.com/RMDLO/COCOpen-OpenCV/commit/42782ee38cc72c51e7aafb560926693e1bd8ade4)

**Comment by ambulocetus18** [comment]
Added scaling and color augmentation parameters to parameters.yml in commit [1c7be1a](https://github.com/RMDLO/COCOpen-OpenCV/commit/1c7be1aa8014d596984d5eb41eac4b0078142bf9)
