### ISSUE TITLE
Add key to label dictionary with value of list of original image names

### ISSUE THREAD

**Issue by JeffersonAero** [RMDLO/COCOpen-OpenCV#9]
Add a dictionary key to the label .json file which, for each generated image, indicates which raw images were combined to produce the image (for example, train/1.png comprises single_wire/1099.png, single_wire/2351.png, and single_wire/4312.png)

This information will be added with a (key, value) pair to the coco_new_obj_seg_sem and coco_new_obj_sem dictionaries. Value = a list of image names, e.g., [“wire/2351.png”, “wire/2362.png”...]
***Note: add the folder the image was pulled from (which should correspond to the object’s category ID) to directory structure of this list
***Will need to set up reading the category name for the object from the folder name where the image is stored (so need to rename folder of “single_wire” images to “wire” images)

**Comment by zhao-harry** [comment]
I am moving forward with this, but note that object segment semantics has since been removed, and there remains only the `coco_sem` dictionary.

**Comment by zhao-harry** [comment]
#30
